networks:
  app-node-network:
    driver: bridge

services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
        VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
        VITE_AUTH0_AUDIENCE: ${VITE_AUTH0_AUDIENCE}
        VITE_AUTH0_CALLBACK_URL: ${VITE_AUTH0_CALLBACK_URL}
    restart: always
    ports:
      - ${FE_PORT}:${FE_PORT}
    networks:
      - app-node-network