networks:
  app-node-network:
    driver: bridge

services:

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./_data/caddy/data:/data
      - ./_data/caddy/config:/config
    networks:
      - app-node-network
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - PORT=${API_PORT}
      - SWAGGER_BE=${SWAGGER_BE}
      - MONGO_URI=${MONGO_URI}
      - BASE_URL=${BASE_URL}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
    networks:
      - app-node-network